name: Deploy
on: workflow_dispatch
jobs:
  deploy-chrome:
    runs-on: ubuntu-latest
    environment: Chrome
    steps:
      - uses: actions/checkout@v3.0.2
      - run: npm install
      - run: npm run deploy:chrome
  deploy-firefox:
    runs-on: ubuntu-latest
    environment: Firefox
    steps:
      - uses: actions/checkout@v3.0.2
      - run: npm install
      - run: npm run deploy:firefox