name: Deploy
on:
  release:
    types: [released]
jobs:
  deploy-chrome:
    runs-on: ubuntu-latest
    environment: chrome
    steps:
      - run: npm install
      - run: npm run deploy:chrome
  deploy-firefox:
    runs-on: ubuntu-latest
    environment: firefox
    steps:
      - run: npm install
      - run: npm run deploy:firefox